name: Lint & Static Analysis

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --no-scripts

      - name: Run PHPStan
        env:
          APP_ENV: local
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G

      - name: Run Pint
        run: vendor/bin/pint

      - name: Commit linted files
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
